// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// normalize_cols_cpp
NumericMatrix normalize_cols_cpp(SEXP M);
RcppExport SEXP _MetaNeighbor_normalize_cols_cpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_cols_cpp(M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MetaNeighbor_normalize_cols_cpp", (DL_FUNC) &_MetaNeighbor_normalize_cols_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MetaNeighbor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
